services:
  - type: web
    name: student-ms-frontend
    env: static
    buildCommand: npm install && chmod +x build.sh && ./build.sh
    staticPublishPath: ./build
    routes:
      - source: /
        destination: /index.html
      - source: /static/*
        destination: /static/*
      - source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 16
      - key: REACT_APP_API_URL
        value: https://webtechasg-2.onrender.com/api/students
